services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.subconverter.rule=Host(`sub.oxcafebabe.cn`)
      - traefik.http.routers.subconverter.entrypoints=websecure
      - traefik.http.services.subconverter.loadbalancer.server.port=25500
      - traefik.http.routers.subconverter.service=subconverter
      - traefik.http.routers.subconverter.tls.certresolver=leresolver
networks:
  traefik-public:
    external: true
